### PR TITLE
Update to *ring* 0.14.4.

### PR DESCRIPTION
**Pull request by briansmith**
Before:
```
test RustCrypto     ... bench:       2,039 ns/iter (+/- 16)
test orion          ... bench:       2,267 ns/iter (+/- 1)
test rigel_one_shot ... bench:       1,925 ns/iter (+/- 1)
test rigel_stream   ... bench:       1,997 ns/iter (+/- 0)
test ring           ... bench:       2,774 ns/iter (+/- 3)
```

After:
```
test RustCrypto     ... bench:       2,039 ns/iter (+/- 14)
test orion          ... bench:       2,206 ns/iter (+/- 0)
test rigel_one_shot ... bench:       1,922 ns/iter (+/- 0)
test rigel_stream   ... bench:       1,999 ns/iter (+/- 0)
test ring           ... bench:       1,293 ns/iter (+/- 1)
```

### CODE REVIEW

**Comment by brycx** [comment]
Hi @briansmith!

This looks good, I'll check those benchmarks with my machine asap.

I see you mentioned my blogpost in https://github.com/briansmith/ring/commit/a051eb6e3283cd941d48ae5358ac4d8fd35d3e89, would you mind if I updated the blogpost to mention that *ring* has since then adopted the changes mentioned in the blogpost?

**Comment by briansmith** [comment]
Also, it's interesting that RustCrypto's variance is so high even on my system.

**Comment by briansmith** [comment]
One final thing: In your blog post you mentioned that you are mostly interested in embedded devices. Be aware that the performance on an Core i9 system is nothing like the performance on an ARMv7 or ARM Cortex-M4 or anything like that.

To give some idea of that, here's the same benchmarks on my 64-bit Core i7 laptop, `cargo +nightly bench --target=i686-pc-windows-msvc`:
```
test RustCrypto     ... bench:       4,089 ns/iter (+/- 1,215)
test orion          ... bench:       4,552 ns/iter (+/- 406)
test rigel_one_shot ... bench:       4,181 ns/iter (+/- 588)
test rigel_stream   ... bench:       4,261 ns/iter (+/- 258)
test ring           ... bench:       2,382 ns/iter (+/- 258)
```

That's also not accounting for the code size, which often (usually) matters more.

**Comment by brycx** [comment]
> This is probably because you have CPU frequency scaling enabled and probably "turbo" enabled. I ran the benchmarks on a system with all that disabled to get more consistent results.

So I've just now run the benchmarks with CPU frequency scaling turned off  (`echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`) and I'm still seeing variances across all libraries. I'll have to look into Intel Turbo at some other point.

> Your benchmark is mostly measuring the key setup time. Usually the key setup time doesn't matter very much because it's still pretty fast and usually a key can be reused several times and often there are multiple blocks of input data.

This is actually on purpose. I know rigel, as a library, only offers speed benefit to some others based on the key-setup process. Keeping the "pre-processed" SHA512 states, as *ring* does, would certainly be more beneficial when processing any data in general. rigel was mainly an experiment. Though I'll add this usage detail to the blogpost.

> In your blog post you mentioned that you are mostly interested in embedded devices. Be aware that the performance on an Core i9 system is nothing like the performance on an ARMv7 or ARM Cortex-M4 or anything like that.

> That's also not accounting for the code size, which often (usually) matters more.

That interest was mainly based on squeezing as much data into a single array as possible, and supporting `no_std` (one of my first attempts to make something myself with crypto). I didn't expect much of rigel, especially as I had not even tested/benched it on an ARMv7. And regarding the size, it probably doesn't matter that an array of 128 bytes is used when the code is plastered with `#inline(always)` and, when used, the binary size most likely is unacceptable haha.

> It was good to read your blog post and see that it was easy to speed up the key setup. I honestly had no idea that the key setup time in ring would dominate such a benchmark like that.

> Yes, please go ahead and mention in the updated blog post that ring's key setup was modified using some of the ideas in your blog post.

Thank you very much. I really appreciate all the pointers you have given me. I'll add it to the updated post, let me know if you find something missing on it.

Also, rigel has some other dependencies to update, so I won't be using your benchmarks unfortunately. If you are unsatisfied with that, please benchmark it on your machine again, after I've updated it, and I'll update both the post and README here with that.

**Comment by briansmith** [comment]
> Also, rigel has some other dependencies to update, so I won't be using your benchmarks unfortunately. If you are unsatisfied with that, please benchmark it on your machine again, after I've updated it, and I'll update both the post and README here with that.

I don't care. It probably makes sense for you to use numbers from your own hardware so you can update them yourself.

**Comment by briansmith** [comment]
> So I've just now run the benchmarks with CPU frequency scaling turned off (`echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`) and I'm still seeing variances across all libraries. I'll have to look into Intel Turbo at some other point.

I can't remember if you need to reboot after changing the governor settings. I turned mine off in my BIOS because that's the most reliable way I could do it.

**Comment by brycx** [comment]
I don't believe so, since I change those every time I use AFL, without rebooting. Though turbo certainly needs to be turned of in BIOS it seems.

**Comment by brycx** [comment]
README and blogpost updated as well.

**Pull request merged**
